[project]
name = "django-benchmark"
version = "0.1.0"
description = "Django performance benchmark profiler"
readme = "README.md"
authors = [
    { name = "Justin Mayer", email = "entroP@gmail.com" },
    { name = "Ontowhee", email = "82607723+ontowhee@users.noreply.github.com" },
    { name = "Žan Anderle", email = "zan.anderle@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "locust>=2.46.6",
]

[project.optional-dependencies]
gunicorn = [
    "gunicorn>=23.0.0",
]
example-app = [
    "django==6.1.1",
]
results-site = [
    "pelican>=4.11.0",
]

[project.scripts]
benchmark = "benchmark:main"

[tool.uv.build-backend]
module-name = "benchmark"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
